version: '3.8'

services:
  # Application Services
  service-a:
    build:
      context: ./service-a
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - SERVICE_B_URL=http://service-b:8080
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - SERVICE_NAME=service-a
    depends_on:
      - service-b
      - otel-collector
    networks:
      - weather-network

  service-b:
    build:
      context: ./service-b
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - PORT=8080
      - WEATHER_API_KEY=81729b82816247ab84f171740252004
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - SERVICE_NAME=service-b
    depends_on:
      - otel-collector
    networks:
      - weather-network

  # OpenTelemetry Services
  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55679:55679" # zpages extension
    networks:
      - weather-network

  # Zipkin for tracing visualization
  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"
    networks:
      - weather-network
      
  # Servi√ßo para testar a conectividade de rede
  network-test:
    image: alpine:latest
    command: sh -c "apk add --no-cache curl && while true; do echo 'Testing connectivity...'; nc -zv otel-collector 4317; sleep 5; done"
    networks:
      - weather-network
    depends_on:
      - otel-collector

networks:
  weather-network:
    driver: bridge