version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: auctionsDB
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: auctions
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: